Update NZ FIR Boundaries
vatsimnetwork/vatspy-data-project pull request #190
Opened 2020-11-23 23:37 UTC by vatpacais

2020-11-23 23:53 UTC, NelisV requested changes
2 Duplicate vertexes, aside from those looks good 👌.

2020-11-23 23:53 UTC, NelisV commented on FIRBoundaries.dat
> +-40.7038501|175.4030622
```suggestion
```
duplicate vertex

2020-11-23 23:53 UTC, NelisV commented on FIRBoundaries.dat
> +-40.5853802|174.986144
```suggestion
```
duplicate vertex

2020-11-24 00:17 UTC, Adrian2k commented
Did you remeber to lower the point count by 1? If not VATSpy will throw an error message at you.

2020-11-24 00:19 UTC, vatpacais commented
I'll resubmit_

2020-11-24 07:58 UTC, Adrian2k approved these changes

2020-11-25 23:22 UTC, NelisV commented
No need to worry about those errors mate :) Looks good now. 
![image](https://user-images.githubusercontent.com/42404718/100291209-6feaac00-2f7d-11eb-839f-23d230a364e2.png)

2020-11-25 23:22 UTC, NelisV approved these changes

2020-11-25 23:23 UTC, merged