Added SBVC
vatsimnetwork/vatspy-data-project pull request #193
Opened 2020-11-24 15:54 UTC by obb12

2020-11-25 22:48 UTC, Adrian2k requested changes
Change is approved by VATBRZ, however we are soring airports alphabetically. Can you move the entry to its correct position so it remains sorted alphabetically?

2020-11-25 23:12 UTC, NelisV commented
this one is for @Adrian2k ;)

2020-11-25 23:13 UTC, NelisV approved these changes

2020-11-26 04:46 UTC, obb12 commented
Changed order

2020-11-26 09:11 UTC, prryplatypus approved these changes

2020-11-26 12:27 UTC, Adrian2k approved these changes

2020-11-26 12:27 UTC, merged