Add subsectors in VATPRC airspace & Adjust boundaries
vatsimnetwork/vatspy-data-project pull request #209
Opened 2020-12-06 08:16 UTC by websterzh

That resolves the issue in #161 (Hopefully.)

2020-12-17 22:59 UTC, NelisV requested changes
Few duplicates, the borders look really nice 👍. 
Although please remove the domestic changes to the russian sectors if not aligned with VATRUS staff.

2020-12-17 22:59 UTC, NelisV commented on FIRBoundaries.dat
> +30.441667|81.625000
duplicate

2020-12-17 22:59 UTC, NelisV commented on FIRBoundaries.dat
> +28.516667|97.583333
duplicate

2020-12-17 22:59 UTC, NelisV commented on FIRBoundaries.dat
> +28.417089|96.262853
duplicate

2020-12-17 22:59 UTC, NelisV commented on FIRBoundaries.dat
> +28.417089|96.262853
duplicate

2020-12-17 22:59 UTC, NelisV commented on FIRBoundaries.dat
> +28.516667|97.583333
duplicate

2020-12-17 22:59 UTC, NelisV commented on FIRBoundaries.dat
> +39.500000|119.866667
duplicate

2020-12-17 22:59 UTC, NelisV commented on FIRBoundaries.dat
> +42.216667|80.250000
duplicate

2020-12-18 05:27 UTC, websterzh commented
> Although please remove the domestic changes to the russian sectors if not aligned with VATRUS staff.
We made some changes here just to align the country border. We have noticed the same kind of "gaps" exists as well somewhere there so we did some minor adjustments to eliminate them.

2020-12-18 09:59 UTC, NelisV commented
AIRAC 2013 version:
![image](https://user-images.githubusercontent.com/42404718/102601107-01ce7a80-4120-11eb-842b-6058495d5ade.png)

This PR:
![image](https://user-images.githubusercontent.com/42404718/102601142-0bf07900-4120-11eb-8d98-8a3681db9053.png)

2020-12-19 05:34 UTC, websterzh commented
Fixed! I didn't spot that before. Also fixed the missing boundary point in ZMUB.

2020-12-21 21:43 UTC, NelisV approved these changes
Looks good!

2020-12-22 07:12 UTC, Adrian2k approved these changes

2020-12-22 07:12 UTC, merged