Corrected LTFE location
vatsimnetwork/vatspy-data-project pull request #220
Opened 2020-12-23 02:21 UTC by within7

Corrected LTFE location

2020-12-28 17:23 UTC, Adrian2k commented on VATSpy.dat
> -LTAB|Ankara-Guvercinlik|39.93306|32.75||LTAA|0
Any reason for this?
Why is the name now only "-Guvercinlik" with the - symbol?

2020-12-28 17:23 UTC, Adrian2k commented on VATSpy.dat
> +LTBB|Istanbul|LTBA|LTBB
Any reason why both LTAA and LTBB has LTBA as prefix position?

2020-12-30 15:01 UTC, NelisV requested changes
@within7 please have a look at adrian's comments

2021-01-22 07:44 UTC, Adrian2k commented
Closing this as there has been no reply.

2021-01-22 07:44 UTC, closed without merging