LOVV Update
vatsimnetwork/vatspy-data-project pull request #311
Opened 2021-04-20 16:57 UTC by seelenkrieger

Removed LOVV_S_CTR and LOVV_N_CTR
addet LOVV-FL165B

2021-04-20 16:58 UTC, seelenkrieger commented
and for info, we are aware that LOVV-FL165B will never light up, its more info for Pilots

2021-04-22 20:51 UTC, Adrian2k approved these changes

2021-04-22 21:42 UTC, NelisV requested changes
Same here as explained in #309. please adjust the sector names and we'll review again.

2021-04-22 22:04 UTC, seelenkrieger commented
> Same here as explained in #309. please adjust the sector names and we'll review again.
I don't see the point of it, what the different would be naming a sector LOVV-W instead of LOVV-FL165B but will respect that.

2021-05-13 14:20 UTC, NelisV approved these changes

2021-05-13 14:20 UTC, merged