VATNZ Pacific Positions Update
vatsimnetwork/vatspy-data-project pull request #528
Opened 2022-04-19 07:28 UTC by dirtyformal

Hey there,

VATNZ has started a Pacific Refresh project, aiming to modernise and overhaul our Pacific positions. As a part of this, we have chosen to do the following -

- Reformat **NSFA_CTR** from a non-standard FIR into a Enroute position. This covers both Western and Eastern Samoa.
- Create **NTTC_CTR** (Tahiti Control). This is an Enroute position in the NTTT FIR that provides both a Class D/E service around the island of Tahiti/Moorea/Bora.
- Create **NCRG_CTR** (Rarotonga Control). This is an Enroute position in the NZZO FIR that provides a Class D Enroute service to the Cook Islands.

These are not sub-sector splits - only new Enroute positions that do not have any existing coverage. I have also provisionally discussed this PR with Niels over Discord a handful of days ago.

Happy to answer any questions!

2022-04-19 13:18 UTC, Adrian2k commented on VATSpy.dat
> +NTTC|Tahiti||NTTC
These will be called "Tahiti Center" on VATSpy as you have not defined the callsign ending on line 120:

French Polynesia|NT|

Make it 
French Polynesia|NT|Control

2022-04-19 13:18 UTC, Adrian2k commented on VATSpy.dat
> +NCRG|Rarotonga|NCRG
Same as on NTTT but line 92 - Cook Islands|NC|

2022-04-19 13:23 UTC, Adrian2k commented on VATSpy.dat
> +NZWN|Wellington|-41.335264|174.803487|WLG|NZCT|0
By the look of it, WLG is not used as a logon for this airport, atleast I can not find it being used. However NZWN_DEL/GND/TWR/APP is being used.

If this is correct, then we should only have one entry for the airport, being `NZWN|Wellington|-41.335264|174.803487|NZWN-F|NZCT|0`

2022-04-19 23:54 UTC, dirtyformal commented
@Adrian2k - Thanks for taking a look over it! You're quite right - those positions are meant to have the "Control" terminology over the "Centre" term. Thank you for that!

I've also amended the WLG error.

2022-04-21 18:19 UTC, NelisV requested changes
![image](https://user-images.githubusercontent.com/42404718/164527127-f69d402c-6f57-422e-83f4-e24537362e64.png)
Ah, sorry i'm a bit late with reviewing this, but you need to move these polygons to the other side of the antimeridian (east of -180).

2022-04-21 18:23 UTC, Adrian2k approved these changes
The VATSpy.dat file is good now.
Firboundaries needs to be resolved as Niels noted, so he will add the final approveal once its ready.

2022-04-21 23:19 UTC, dirtyformal commented
> Ah, sorry i'm a bit late with reviewing this, but you need to move these polygons to the other side of the antimeridian (east of -180).

Sorry it took me a hot minute to figure out how damn maps work, but I've found and fixed a problem on our end which should rectify the meridian issues.

Thanks for your patience with this - I appreciate the help from both of you!

2022-04-22 07:33 UTC, NelisV approved these changes

2022-04-22 07:33 UTC, NelisV commented
Ah no problem, thanks for taking the effort. All looking good now ;)

2022-04-25 20:09 UTC, NelisV requested changes
So we do have a conflict, i think it's because you based this on the master branch instead of 2204. I think it's best to move this to 2205 as you already suggested.

2022-04-25 23:43 UTC, dirtyformal commented
> So we do have a conflict, i think it's because you based this on the master branch instead of 2204. I think it's best to move this to 2205 as you already suggested.

My apologies for the error - I'll give it a look when I get home. I may even close this PR, and open a new one based on 2204.

Would there be any potential for a mid-cycle release - or is that off the table?

2022-04-26 09:00 UTC, NelisV commented
> > So we do have a conflict, i think it's because you based this on the master branch instead of 2204. I think it's best to move this to 2205 as you already suggested.
> 
> My apologies for the error - I'll give it a look when I get home. I may even close this PR, and open a new one based on 2204.
> 
> Would there be any potential for a mid-cycle release - or is that off the table?

Nope, we really try to stick to the airac cycles for our own sanity. So 2205 would be the next opportunity.

2022-05-09 04:55 UTC, dirtyformal commented
Closing this PR in order to base off the 2205 branch - hopefully solving the conflicts.

2022-05-09 04:55 UTC, closed without merging