AIRAC 2205
vatsimnetwork/vatspy-data-project pull request #542
Opened 2022-05-20 13:54 UTC by Adrian2k

2022-05-20 14:10 UTC, NelisV requested changes
Something is messed up, investigating. 
![image](https://user-images.githubusercontent.com/42404718/169546084-bd08fed3-ae36-402a-b7f7-6d7e73687471.png)

2022-05-20 14:28 UTC, NelisV commented
![image](https://user-images.githubusercontent.com/42404718/169549476-18f0a5b7-183a-475a-85e1-8526155d9954.png)
the issue is in #538 @Adrian2k could you add a '|' here?

2022-05-21 11:08 UTC, NelisV approved these changes

2022-05-21 20:29 UTC, mbozwood approved these changes

2022-05-21 20:29 UTC, merged