Update UHMM boundaries + Delete UHPP boundaries
vatsimnetwork/vatspy-data-project pull request #607
Opened 2022-10-30 15:21 UTC by theShpuntik

2022-11-04 22:38 UTC, Adrian2k requested changes

2022-11-04 22:38 UTC, Adrian2k commented on Boundaries.geojson
> -  { "type": "Feature", "properties": { "id": "UHPP", "oceanic": "0", "label_lon": "164.3", "label_lat": "57.0", "region": "EMEA", "division": "VATRUS" }, "geometry": { "type": "MultiPolygon", "coordi
Removoal of a FIR also requires the FIR to be removed in VATSpy.dat.
You also have to assosiate all the airports that has UHPP as a FIR to another FIR.

2022-11-04 22:39 UTC, Adrian2k commented on Boundaries.geojson
> -  { "type": "Feature", "properties": { "id": "UHPP", "oceanic": "0", "label_lon": "164.3", "label_lat": "57.0", "region": "EMEA", "division": "VATRUS" }, "geometry": { "type": "MultiPolygon", "coordi
Ok, I see the changes is done in #608 
But please next time do not seperate changes into two pull requests.

2022-11-04 22:40 UTC, Adrian2k approved these changes

2022-11-08 10:19 UTC, NelisV commented
@theShpuntik Please resolve the merge conflict here.

2022-11-08 10:19 UTC, NelisV requested changes
@theShpuntik Please resolve the merge conflict in this pr.

2022-11-10 09:42 UTC, NelisV approved these changes

2022-11-10 09:42 UTC, merged