changed Langen North identifiers
vatsimnetwork/vatspy-data-project pull request #611
Opened 2022-11-06 21:30 UTC by LeoKle

Following the changes of south Langen logons on 5th October, Langen North has introduced new logons.
I also fixed an error, in which "Hamm" Sector was shown as "Pad High" sector.

2022-11-06 22:24 UTC, Adrian2k commented
It is not really a mistake. Both entries point to the same FIR definition, hence their name need to be the same to avoid errors.

EDGG-PAH and EDGG-HMM FIR's are not in the Boundaries.geojson file and EDGG-P needs to be reasigned a different code.

2022-11-08 10:21 UTC, NelisV requested changes
Please see comment above

2022-12-08 11:16 UTC, NelisV approved these changes

2022-12-09 19:36 UTC, Adrian2k approved these changes

2022-12-09 19:36 UTC, merged