Update Australian Positions
vatsimnetwork/vatspy-data-project pull request #675
Opened 2023-05-05 05:21 UTC by chrisg06

2023-05-13 23:16 UTC, Adrian2k requested changes

2023-05-13 23:16 UTC, Adrian2k commented on VATSpy.dat
> +YBBN|Brisbane|-27.384167|153.1175|BN-W|YINL|0
While it has not been done in the existing file, please change the additional YBBN entries to have the pseudo id to 1.

**Example:**
```
YBBN|Brisbane|-27.384167|153.1175|BN|YINL|0
YBBN|Brisbane|-27.384167|153.1175|BN-S|YINL|1
YBBN|Brisbane|-27.384167|153.1175|BN-F|YINL|1
YBBN|Brisbane|-27.384167|153.1175|BN-N|YINL|1
YBBN|Brisbane|-27.384167|153.1175|BN-W|YINL|1
```

2023-05-21 12:15 UTC, chrisg06 commented
@Adrian2k updated to address comment.

2023-05-21 18:44 UTC, Adrian2k approved these changes

2023-05-25 09:23 UTC, NelisV approved these changes

2023-05-25 09:23 UTC, merged