update South korea inner boundaries
vatsimnetwork/vatspy-data-project pull request #680
Opened 2023-05-22 06:40 UTC by lancard

- CTA (RKRR / RKDA) modified by AIRAC

2023-05-25 09:34 UTC, NelisV requested changes
There seems to be an error in RKDA cutting through North Korea. Please check and ammend. 
![image](https://github.com/vatsimnetwork/vatspy-data-project/assets/42404718/53a9353e-fcae-40d7-8456-d73c6f03e938)
![image](https://github.com/vatsimnetwork/vatspy-data-project/assets/42404718/2c572154-9650-4935-8063-4aa9743ddde4)

2023-05-25 11:48 UTC, lancard commented
sorry. it's my mistake :) typo.

2023-06-18 04:45 UTC, lancard commented
updated. could you review again?

2023-06-19 09:06 UTC, NelisV approved these changes

2023-06-19 09:17 UTC, merged