Update VATSpy.dat
vatsimnetwork/vatspy-data-project pull request #731
Opened 2023-10-28 19:05 UTC by seelenkrieger

Adjusted LOVV subsector to responsive ATC-Station

## Description of changes

## Reason and motivation

## Approved contributior

- [ ] I am on the approved contributers list
- [ ] I have sent an request by email to get approved
- [ ] Someone on the approved contributer list will review this request

2023-10-30 17:24 UTC, Adrian2k approved these changes

2023-10-31 14:35 UTC, NelisV requested changes
Cannot merge like this, as it'll overwrite our template and readme, please rebase on the right branch and start a new PR.

2023-11-01 00:21 UTC, Adrian2k commented
No its fine, can be merged.

2023-11-02 09:25 UTC, NelisV approved these changes

2023-11-02 09:25 UTC, merged