Updated EDWW Sectors and Stations [2311]
vatsimnetwork/vatspy-data-project pull request #739
Opened 2023-11-03 22:16 UTC by chrisgutierrez96

## Description of changes
-Changed EDWW Sectors to reflect new split options.
-Adjusted EDGG Sector boundaries to match.
-Updated EDWW Stations to show in the correct location on map.

## Reason and motivation
In EDWW we recently updated our possible sector splits. We can now split into north and south regions.
This will help to manage traffic in a smaller sector and also will help Center students to learn more in a smaller area.

## Approved contributior
chrisgutierrez96 & jannikvogel

- [ x ] I am on the approved contributers list
- [ x ] I have sent an request by email to get approved
- [ x ] Someone on the approved contributer list will review this request

2023-11-04 12:43 UTC, jannikvogel approved these changes
lgtm. @NelisV @Adrian2k

2023-11-05 15:34 UTC, chrisgutierrez96 commented
@Adrian2k Is there any chance we can release this change as soon as possible? It's a fairly big change which I could not complete in time before the 2311 release.

2023-11-15 19:03 UTC, Adrian2k commented on VATSpy.dat
> +EDWW-B|Bremen Radar (Boerde) - Bremen|EDWW_B|EDWW-B
There is two entries for EDWW_B, this one and ``EDMM-G|Muenchen ACC (Gera) - Muenchen|EDWW_B|EDMM-G``

Not sure if this would even work..

2023-11-15 19:29 UTC, Adrian2k commented
Several misalligned borders for the EDWW-D sector

## 1
New point introduced which does not exist in the existing EDWW FIR's or EDGG FIR's.
![image](https://github.com/vatsimnetwork/vatspy-data-project/assets/35482228/f3953880-c202-4985-898e-4b0dd1b993cc)

## 2
New point which should be included in the EHAA and EHMC FIR's to match the borders.
![image](https://github.com/vatsimnetwork/vatspy-data-project/assets/35482228/bac6ed70-54a4-4009-ad8a-dfc045ce98bb)

## 3
Several new points in the in EDWW-D which does not align to existing borders
![image](https://github.com/vatsimnetwork/vatspy-data-project/assets/35482228/edeae9b7-53ac-49ae-9e5d-f60a37bc6579)
![image](https://github.com/vatsimnetwork/vatspy-data-project/assets/35482228/5f8b79bb-e5d3-40c4-8465-e8df705ba311)

## 4
More misalignments 
![image](https://github.com/vatsimnetwork/vatspy-data-project/assets/35482228/86969ee9-2f2b-4d6b-a964-b36f1d60c968)

2023-11-15 19:29 UTC, Adrian2k requested changes
see above

2023-11-16 13:43 UTC, NelisV approved these changes

2023-11-16 13:44 UTC, NelisV requested changes
See adrians review

2023-11-20 01:37 UTC, chrisgutierrez96 commented
Ok will fix asap.

2023-11-20 03:09 UTC, chrisgutierrez96 commented
Ok I am getting frustrated by the minute. I am trying to make the changes and realign the boundaries, but now the boundary file is corrupt, and I can not seem to find the reason. I tried to add the vertex to EHAA and EHMC so that should work but aligning the boundary did not so can someone please check what the error is?

2023-11-25 15:04 UTC, chrisgutierrez96 commented
All changes complete.

2023-12-01 20:43 UTC, Adrian2k commented
File is in conflict - @chrisgutierrez96

2023-12-02 18:34 UTC, chrisgutierrez96 commented
What exactly is in conflict? I cannot find the error.

2023-12-06 09:54 UTC, NelisV commented
@chrisgutierrez96 Best way to solve this would be to rebase your changes on top of the current 2312 branch. Can't merge like this.

2023-12-06 09:55 UTC, NelisV requested changes
Pending resolution of the merge conflict.

2023-12-06 11:04 UTC, jannikvogel commented
> @chrisgutierrez96 Best way to solve this would be to rebase your changes on top of the current 2312 branch. Can't merge like this.

I think Chris is no longer involved in the Bremen OPS Team. You can expect a PR in a few hours from me solving the merge conflicts with the EDMM one.

2024-01-23 13:37 UTC, closed without merging