EDMM: update eastern station designators [2401]
vatsimnetwork/vatspy-data-project pull request #777
Opened 2024-01-20 15:40 UTC by globin

## Description of changes
Station designators are being changed with AIRAC 2401

## Approved contributior?

- [ ] I am on the approved contributers list
- [ ] I have sent an request by email to get approved
- [x] Someone on the approved contributer list will review this request

2024-01-20 15:41 UTC, jannikvogel approved these changes

2024-01-23 13:55 UTC, Adrian2k requested changes
You will need to change the airspaces too.

There is no airspace with the name EDMM-HOF, EDMM-GER in the dataset.

2024-01-23 15:06 UTC, globin commented
Fixed, sorry missed those.

2024-01-23 18:51 UTC, Adrian2k approved these changes

2024-01-23 18:51 UTC, merged