Lfmm sectors updates
vatsimnetwork/vatspy-data-project pull request #898
Opened 2024-11-14 13:56 UTC by ClipperWings

## Description of changes
Removes LFMM-S and cleans up the sector boundaries between LFFF and LFBB. Splits are now correctly defined as currently, 

## Reason and motivation
We need certain sectors to pop up and not the entire FIR

Avoids getting hammered when opening the FIR so splits are required / necessary 

## Approved contributior?
- [ X ] I am on the approved contributors list

2024-11-29 21:31 UTC, Adrian2k commented
Please fix conflict in file

2024-11-30 10:12 UTC, ClipperWings commented
Should be resolved. Thanks for the info.

2024-12-28 01:18 UTC, Adrian2k commented
Hello - sorry for the late review of this.
Usually it is not me who do the review of the geosjon files, but I will try my best.

Some of these may be excisting issues, but it will be good to get them resolved while we are editing these sectors.

I noticed some border overlapping each other:

## Top of LFMM FIR
![image](https://github.com/user-attachments/assets/44db05a0-7e5f-4a04-9156-406507c37d3b)

## Between LFMM + LIMM
![image](https://github.com/user-attachments/assets/dce34133-b4ad-43b8-808f-f3135c0d05cf)s

## Between LFMM + LECB
![image](https://github.com/user-attachments/assets/19f46d9c-3e5c-4e8d-828f-c5547dd599a7)


Other than this, it looks good for me

2024-12-28 01:18 UTC, Adrian2k requested changes
as above

2025-01-06 21:05 UTC, herver commented
It should hopefully be good now
(I'm not quite sure how to spot these in a more systematic way in QGis, it'd be useful if you have some pointers 😅 )

2025-01-10 08:29 UTC, NelisV approved these changes

2025-01-10 23:51 UTC, Adrian2k approved these changes

2025-01-10 23:51 UTC, merged