LIRR Roma subsectors
vatsimnetwork/vatspy-data-project pull request #904
Opened 2024-11-30 11:12 UTC by TomDS66

## Description of changes

Added Roma subsectors

## Reason and motivation

New sectors have been added since AIRAC 2410

## Approved contributior?

- [x] I am on the approved contributers list
- [ ] I have sent an request by email to get approved
- [ ] Someone on the approved contributer list will review this request

2024-12-28 01:37 UTC, Adrian2k requested changes
Hello - sorry for the late review of this.
Usually it is not me who do the review of the geosjon files, but I will try my best.

The polygons look good, while I had to spend some time actually understanding what sectors you had added.

Please correct the 3 VATSpy.dat entries :)

2024-12-28 01:37 UTC, Adrian2k commented on VATSpy.dat
> +LIRR|Roma ACC - NE - Roma|LIRR_NE1|LIRR
LIRR_NE1 entry not required here - any logon not defined below will automatically revert to the whole LIRR FIR

2024-12-28 01:37 UTC, Adrian2k commented on VATSpy.dat
> +LIMM|Milano ACC - EN|LIMM_EN|LIMM
LIMM_EN entry not required here, same as LIRR

2024-12-28 01:37 UTC, Adrian2k commented on VATSpy.dat
> +LIPP|Padova ACC - NE|LIPP_NE|LIPP
Same thing here

2025-01-10 08:30 UTC, NelisV approved these changes

2025-01-10 23:51 UTC, Adrian2k approved these changes

2025-01-10 23:51 UTC, merged