update LRBB sectorisation
vatsimnetwork/vatspy-data-project pull request #916
Opened 2024-12-22 13:19 UTC by tgpetrica

## Description of changes

- remove LRUB UIR
- update LRBB FIR boundary to cover LUUU FIR
![image](https://github.com/user-attachments/assets/3f98c5ff-9a1b-4c37-a750-b5a7be4dd701)
- add LRBB-A subsector of LRBB FIR
![image](https://github.com/user-attachments/assets/02f57355-1eef-4ab8-9747-ecc69be53bf5)
- add LRBB-N subsector of LRBB FIR
![image](https://github.com/user-attachments/assets/46290d6e-dc09-4335-8b93-9f9c576483b7)

## Reason and motivation

- to display active sectors correctly

## Approved contributior?

- [X] I am on the approved contributers list
- [ ] I have sent an request by email to get approved
- [ ] Someone on the approved contributer list will review this request

2024-12-22 15:43 UTC, Adrian2k approved these changes

2024-12-28 02:01 UTC, Adrian2k commented
Checked the FIR entries now - look all good.

However we have a conflict in the file - could you please rebase this so the conflict get resolved?

2024-12-28 02:21 UTC, Adrian2k submitted a review, later dismissed
as above

2025-01-10 08:37 UTC, NelisV requested changes
@tgpetrica see adrian's request above. Polygons do look good.

2025-04-19 08:20 UTC, Adrian2k approved these changes

2025-04-19 08:20 UTC, daniluk4000 commented
Stand by...

2025-04-19 08:23 UTC, daniluk4000 approved these changes
![image](https://github.com/user-attachments/assets/2504f5d8-75b9-4a91-aeeb-50b29e297bc5)

LGTM

2025-04-19 08:23 UTC, merged